[package]
name = "spindalis"
version = "0.4.0"
edition = "2024"

[lib]
name = "spindalis"
path = "src/lib.rs"

[dependencies]
spindalis_core = { path = "../spindalis_core" }
spindalis_macros = { path = "../spindalis_macros" }
